#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - source

# Maximum number of concurrent jobs for the project
max_jobs: 1


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Ubuntu1804

# set clone depth
clone_depth: 5

# environment variables
environment:
  GIT_USER_EMAIL: debe3721@gmail.com
  GIT_USER_NAME: PresentKim
  GIT_USER_TOKEN:
    secure: S1QYp6oZpUMJI4EszvBaLUFq6pr2dtweoP3P+uF+l6XDQ+CyojHnG2B+rH1NqCto
    cache:
      - 'node_modules'  # local npm modules
      - '%APPDATA%\npm-cache' # npm cache

# build cache to preserve files/folders between builds
cache:
  - 'node_modules'  # local npm modules
  - '%APPDATA%\npm-cache' # npm cache

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:GIT_USER_TOKEN):x-oauth-basic@github.com`n"
  - git config --global user.email $($env:GIT_USER_EMAIL)
  - git config --global user.name $($env:GIT_USER_NAME)

# scripts that run after cloning repository
install:
  - npm install --global npm@latest
  - npm install hexo-cli -g
  - npm install

# to run your custom scripts instead of automatic MSBuild
build_script:
  - hexo clean
  - hexo generate

# on successful build
on_success:
  - hexo deploy


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: public
    name: source.zip
