language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - git clone https://github.com/hexojs/hexo-theme-unit-test generate_test
  - git clone https://github.com/ikeq/hexo-theme-inside.git generate_test/themes/landscape
  - cd generate_test
  - npm install
  - hexo g & hexo g
  - cd ..
